server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 1.12.222.228:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - name: Basic






service-url:
  nacos-user-service: http://nacos-gateway-provider
